// Website building packages sold directly to customers (not marketplace listings).
// Phase 5 will add admin management; for now these are the confirmed 5 tiers.
// All prices are in NGN (site displays multi-currency via currencies.js rates).
module.exports = [
  {
    key: "starter",
    name: "Online Presence",
    code: "Starter",
    tagline: "Get your business online fast with a clean, professional 5-page website.",
    price: 120000,
    pages: "Up to 5 pages",
    delivery: "10-14 days",
    support: "1 month support",
    popular: false,
    features: [
      "Mobile-responsive design",
      "Contact & enquiry form",
      "WhatsApp click-to-chat button",
      "About, Services, Contact pages",
      "Social media links",
      "Basic on-page SEO",
      "Live in 10-14 days",
    ],
  },
  {
    key: "standard",
    name: "Business Growth",
    code: "Standard",
    tagline: "A fuller site that grows with you - more pages, a blog and deeper integrations.",
    price: 250000,
    pages: "Up to 10 pages",
    delivery: "2-3 weeks",
    support: "3 months support",
    popular: true,
    features: [
      "Everything in Online Presence",
      "Up to 10 pages",
      "Blog with content management",
      "Booking or enquiry automation",
      "Google Maps & directions",
      "Advanced SEO (schema + sitemap)",
      "Analytics setup",
      "Live in 2-3 weeks",
    ],
  },
  {
    key: "ecommerce",
    name: "E-Commerce Store",
    code: "Gold",
    tagline: "Sell online 24/7 with a full store, secure payments and an order dashboard.",
    price: 420000,
    pages: "Store + product pages",
    delivery: "3-4 weeks",
    support: "6 months support",
    popular: false,
    features: [
      "Everything in Business Growth",
      "Online store with up to 20 products",
      "Paystack payment integration",
      "Order & inventory management",
      "Secure customer checkout",
      "Sales & delivery notifications",
      "Training on managing your store",
      "Live in 3-4 weeks",
    ],
  },
  {
    key: "corporate",
    name: "Corporate Website",
    code: "Platinum",
    tagline: "A flagship site for established brands - full custom design and priority turnaround.",
    price: 650000,
    pages: "Fully custom",
    delivery: "4-6 weeks",
    support: "12 months priority support",
    popular: false,
    features: [
      "Everything in E-Commerce Store",
      "Fully custom design & branding",
      "Multiple admin users & roles",
      "Portals, dashboards or member areas",
      "Dedicated account manager",
      "Priority support for 12 months",
      "Detailed launch & handover",
      "Live in 4-6 weeks",
    ],
  },
  {
    key: "custom",
    name: "Custom Solution",
    code: "Custom",
    tagline: "Something bigger in mind? Tell us what you need and we'll quote it precisely.",
    price: null,
    pages: "Tailored",
    delivery: "Quoted per project",
    support: "Tailored",
    popular: false,
    features: [
      "Anything beyond the packages above",
      "Multi-vendor or marketplaces",
      "Mobile apps or web platforms",
      "Complex integrations & automations",
      "Fixed, transparent quote - no surprises",
    ],
  },
];